### ISSUE TITLE
All mods show up in the mod resource pack list.

### ISSUE THREAD

**Issue by OroArmor** [QuiltMC/quilted-fabric-api#154]
This probably also affects datapacks. 

Definitely caused by lines 62-71 in ModResourcePackUtil.java. Not sure of the side effects of removing.

**Comment by Useott** [comment]
Happens on Fabric too, seems to be an issue there

**Comment by ghost** [comment]
I have the same issue, for me it's only happening on quilt, not on fabric (tried on 1.20.4)

**Comment by OroArmor** [comment]
This is fixed in 1.21.1+ (when released), and probably wont be ported back to earlier versions.

**Comment by JCollins2048** [comment]
> This is fixed in 1.21.1+ (when released), and probably wont be ported back to earlier versions.

So, that's it, then?  No one's going back-port this?  People still using 1.20.4 are just *stuck* with a big, ugly pile of mods in their Resource Pack lists?  And what about how this **disables** the ability to save Resource Pack setups in that specific version?  That's kind of a problem!

I genuinely feel that the answer of "fixed in next version, issue closed" isn't good enough.  You allow users to install newer versions of the loader on *numerous* versions of *Minecraft*.  If this is something you can fix on your end, then why not fix it for the specific afflicted version, **1.20.4**, instead of moving along?

Your post indicates that it's possible.  If this is Mojang's fault, instead, and it's nothing *you* can fix for this specific version, or of it would be too much of a pain in the butt to bother with, then fine.  Just say so.  But as it is, dusting your hands and looking ahead to the future like a pretty lame way to deal with a problem that *still exists* for people using older clients.

That's how I see it, anyway…

**Comment by OroArmor** [comment]
The problem exists due to a lack of my own time to dedicate to this project. Because of this, if I am able to fix it in a future version, that is great, but I already struggle keeping up with the latest version. How am I supposed to support many previous versions as well. I understand your frustration, but there is only so much I can do.

**Comment by JCollins2048** [comment]
Ah, well that's different!  It's also perfectly reasonable.

Thank you for taking the time to explain, and I apologize for my somewhat aggressive post.  In the grand scheme, this really is a tiny thing that probably won't be relevant in the near-future.  It just _happened_ to be relevant to _me_ at this specific time.

Life is weird like that…
