### ISSUE TITLE
[Crash: In-Game] 1.19.3 game crashes when creating a new world on quilt with Unicopia

### ISSUE THREAD

**Issue by MimzyFang** [QuiltMC/quilted-fabric-api#60]
the game crashes when entering the creating a new world screen on quilt when quilted fabric api and Unicopia https://github.com/Sollace/Unicopia/releases/tag/1.0.0-beta.29 is installed. I talked to the developer, and he told me to report the issue to you.

log:
https://mclo.gs/seKi08y

**Comment by EnnuiL** [comment]
Fixed on the next QFAPI 1.19.3 update!

![A screenshot of a pegasus flying around the world](https://user-images.githubusercontent.com/85590273/215002854-09721fff-ad2a-4f95-9bdf-9f964a1dd7af.png)

This issue was pretty interesting, because despite ~~three~~ two interfaces sharing the exact same method? There was some interesting trickery needed in order to actually make the relevant Fabric interface (DynamicRegistryView) recognize that the method was being implemented; I do hope I can clear it up in the future

**Comment by EnnuiL** [comment]
ugh I shipped the wrong fix; An update will be released asap
