### ISSUE TITLE
QFAPI doesn't access widen MusicDiscItem

### ISSUE THREAD

**Issue by MoriyaShiine** [QuiltMC/quilted-fabric-api#62]
Found this crash by trying to load Dimensional Doors on a quilt instance.

QFAPI 5.0.0-alpha.9_qsl-4.0.0-beta.5_fapi-0.72.0_mc-1.19.3
Dimensional Doors 5.1.0-1.19.3

Relevant issue https://github.com/DimensionalDevelopment/DimDoors/issues/330
Log https://gist.github.com/MoriyaShiine/dabf89d20f214a24d3e87260231f0cb8

**Comment by EnnuiL** [comment]
This has been caused by me assuming that QSL already generated item constructors instead of only QFAPI doing it, and also by the move to generating the AW instead of having the hacky solution of manual modifications; This is interesting, because I feel like QSL should have something! We'll see what we'll end doing

This will be fixed on the next QFAPI 1.19.3 release
