### ISSUE TITLE
Update to Fabric API 0.73.0

### ISSUE THREAD

**Issue by Swedz** [QuiltMC/quilted-fabric-api#64]
QFAPI should update to use the 0.73.0 version of FAPI since it resolves a major issue with air items being null.
> Fix ItemStack.EMPTY.getItem() rarely returning null due to threading (#2826) (Technici4n)

**Comment by EnnuiL** [comment]
An update will hopefully begin tomorrow (Sunday); I've waited to do this upstream sync instead of doing a same-day update because I wanted to release it with an important QSL update that will hopefully release tomorrow, which adds a new API and also has an important fix of it's own to a bug which had been breaking mod compatibility in general

**Comment by EnnuiL** [comment]
The upstream sync has been done with QFAPI v5.0.0-beta.1 and v4.0.0-beta.27
