### ISSUE TITLE
Weird crash that doesnt happen with FAPI

### ISSUE THREAD

**Issue by OroArmor** [QuiltMC/quilted-fabric-api#91]
https://forum.quiltmc.org/t/quilt-fabric-api-crash/823

**Comment by comp500** [comment]
This is a manifestation of the mixin conflict between Satin and the Fabric core shader API, fixed in https://github.com/Ladysnake/Satin/commit/d79fe7f8a3f78afc7df38cc4ae4214afeb484d6e. Due to the load order being different between QFAPI and FAPI the mixin injection crashes immediately rather than silently failing and breaking Satin shaders - the same behaviour as FAPI can be observed using `-Dloader.debug.loadLate=satin`.

I noticed https://github.com/QuiltMC/quilt-standard-libraries/pull/295 for QSL; it might be a good idea to bring this to QFAPI as well, as upstream modules can also cause mixin priority issues.

**Comment by comp500** [comment]
https://github.com/comp500/Indium/issues/188 also shows the same crash; replicable with Satin 1.10.0 and QSL 5.0.0-beta.9+0.76.0-1.19.3
